-- Generated from generator/demo_specs/aws-philippines-remittance-fraud-aml.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-remittance-fraud-aml
-- This is the schema that is actually deployed for PH_REMITTANCE_FRAUD_AML.

-- Alerts fire on the bottom tail of Alerts Generated
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_ALERTS_GENERATED) AS T
  FROM RAW.TRANSACTIONS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ALERTS_GENERATED <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ALERTS_GENERATED), 2) AS AVG_ALERTS_GENERATED,
  ROUND(AVG(f.KPI_FALSE_POSITIVE_RATE), 2) AS AVG_FALSE_POSITIVE_RATE,
  ROUND(AVG(f.KPI_MODEL_PRECISION), 2) AS AVG_MODEL_PRECISION,
  ROUND(AVG(f.KPI_TYPOLOGY_COVERAGE), 2) AS AVG_TYPOLOGY_COVERAGE,
  ROUND(AVG(f.KPI_AVG_INVESTIGATION_TIME), 2) AS AVG_INVESTIGATION_TIME
FROM RAW.TRANSACTIONS f
JOIN RAW.BSP_CIRCULARS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ALERTS_GENERATED), 2) AS AVG_ALERTS_GENERATED,
  ROUND(AVG(f.KPI_FALSE_POSITIVE_RATE), 2) AS AVG_FALSE_POSITIVE_RATE,
  ROUND(AVG(f.KPI_MODEL_PRECISION), 2) AS AVG_MODEL_PRECISION,
  ROUND(AVG(f.KPI_TYPOLOGY_COVERAGE), 2) AS AVG_TYPOLOGY_COVERAGE,
  ROUND(AVG(f.KPI_AVG_INVESTIGATION_TIME), 2) AS AVG_INVESTIGATION_TIME
FROM RAW.TRANSACTIONS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_ALERTS_GENERATED) AS KPI_ALERTS_GENERATED, AVG(KPI_FALSE_POSITIVE_RATE) AS KPI_FALSE_POSITIVE_RATE, AVG(KPI_MODEL_PRECISION) AS KPI_MODEL_PRECISION, AVG(KPI_TYPOLOGY_COVERAGE) AS KPI_TYPOLOGY_COVERAGE, AVG(KPI_AVG_INVESTIGATION_TIME) AS KPI_AVG_INVESTIGATION_TIME FROM RAW.TRANSACTIONS),
     en AS (SELECT SUM(KPI_SAR_FILED) AS KPI_SAR_FILED, SUM(KPI_BLOCKED_TRANSACTIONS) AS KPI_BLOCKED_TRANSACTIONS FROM RAW.BSP_CIRCULARS)
  SELECT 1 AS SORT_ORDER, 'Alerts Generated' AS TITLE, KPI_ALERTS_GENERATED AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_ALERTS_GENERATED)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'SAR Filed' AS TITLE, KPI_SAR_FILED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SAR_FILED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'False Positive Rate' AS TITLE, KPI_FALSE_POSITIVE_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FALSE_POSITIVE_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Blocked Transactions' AS TITLE, KPI_BLOCKED_TRANSACTIONS AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_BLOCKED_TRANSACTIONS) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Model Precision' AS TITLE, KPI_MODEL_PRECISION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_MODEL_PRECISION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Typology Coverage' AS TITLE, KPI_TYPOLOGY_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TYPOLOGY_COVERAGE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Avg Investigation Time' AS TITLE, KPI_AVG_INVESTIGATION_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_INVESTIGATION_TIME), 1) AS DECIMAL(38,1))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
