-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Fraud Detection & AML Compliance
-- ============================================================================
USE DATABASE FRAUD_AML;
USE SCHEMA ML;

-- ML.ANOMALY_DETECTION: AML_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.AML_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.AML_TIMESERIES'),
  SERIES_COLNAME => 'ALERT_TYPE',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'ALERT_COUNT',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.AML_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.AML_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.AML_TIMESERIES'), SERIES_COLNAME => 'ALERT_TYPE', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'ALERT_COUNT'));

-- ML.CLASSIFICATION: FRAUD_RISK_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.FRAUD_RISK_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.ACCOUNT_RISK_SCORE'),
  TARGET_COLNAME => 'IS_SUSPICIOUS'
);

