-- ============================================================================
-- 99_RESET.SQL — Reset Fraud Detection & AML Compliance to clean demo state
-- ============================================================================
USE DATABASE FRAUD_AML;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_PARSE_KYC SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_ACCOUNTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_STR SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.ACCOUNT_RISK_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.STRUCTURING_DETECTION REFRESH;
ALTER DYNAMIC TABLE CURATED.NETWORK_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE CURATED.AML_TIMESERIES REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM FRAUD_AML.RAW.TRANSACTIONS → 5600000
-- SELECT COUNT(*) FROM FRAUD_AML.RAW.KYC_DOCUMENTS → 320000
-- SELECT COUNT(*) FROM FRAUD_AML.CURATED.STRUCTURING_DETECTION WHERE STRUCTURING_PROBABILITY > 0.8 → >40

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_STR RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_ACCOUNTS RESUME;
ALTER TASK IF EXISTS APP.TASK_PARSE_KYC RESUME;
